config/routes.rb
StMichaelsGFC::Application.routes.draw do
 
  resources :players_profiles
  resources :teams
  resources :sign_up_newsletters
  resources :newsletter_st_micahels_gfcs
  resources :newsletters
  resources :users
  resources :sessions
  resources :photos
  resources :events
  resources :pitch_bookings 

  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  root :to => "admin#index"
 
   match "club_history" => "club_history#index" 
   match "fixtures" => "events#index"
   match "admin" => "admin#index"
    match "stmichaelsgfc" => "stmichaelsgfc#index"
  

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  attr_accessible :date, :email, :name, :phone, :reason, :text
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :Age_Category, :Date, :Location, :Opponent, :Time
  
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  attr_accessible :content, :date, :string, :title
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :caption
  attr_accessible :image
  
  has_attached_file :image
    
  
end

app/models/pitch_booking.rb
class PitchBooking < ActiveRecord::Base
  attr_accessible :date, :email, :name, :phone, :reason
end

app/models/players_profile.rb
class PlayersProfile < ActiveRecord::Base
  attr_accessible :age_category, :date_of_birth, :name
  attr_accessible :pic
  
  has_attached_file :pic
end

app/models/sign_up_newsletter.rb
class SignUpNewsletter < ActiveRecord::Base
  attr_accessible :email, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/club_history_helper.rb
module ClubHistoryHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<div id= "right_box">
<h1>Welcome to the Admin Panel
<p>You can Add/Edit/Delete Events and</p>
<p>You can Add/Edit/Delete Bookings</p></h1>
<%= link_to "Events", events_path %><br><br>
<%= link_to "Bookings", pitch_bookings_path %><br><br>
<%= link_to "Newsletters", new_newsletter_st_micahels_gfc_path  %><br><br>
<%= link_to "Newsletters Sign Up", sign_up_newsletters_path  %><br><br>
<%= link_to "Teams", new_players_profile_path %>
<br><br>
</div>
<br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StMichaelsGFC</title>
   <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
   <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
  <div id="user_nav">
  <% if current_user %>
  
    <%= link_to "Log out", log_out_path %>

  <% end %>


</div>
  <div class= "container">
    <header>
    <div class="navbar">
      <div class= "button"><a href= "stmichaelsgfc">News</a></div>
      <div class= "button"><a href= "club_history">Club History</a></div>
      <div class= "button"><a href= "fixtures">Fixtures</a></div>
      <div class= "button"><a href= "newsletter_st_micahels_gfcs">Newsletter</a></div>
      <div class= "button"><a href= "players_profiles">Teams</a></div>
      <div class= "button"><a href= "photos">Photo's</a></div>
      <div class= "button"><a href= "pitch_bookings/new">Bookings</a></div>
         <div class= "button"><a href= "log_in">Log In
         
         </a></div>
   </div>
      <%= image_tag("logo.jpg", :alt => "St Michaels GFC", :class => "round")%>
    </header>

    	<div id= "left_box"> <h1> 

<!-- include jQuery library -->
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<!-- include Cycle plugin -->
<script type="text/javascript" src="http://cloud.github.com/downloads/malsup/cycle/jquery.cycle.all.latest.js"></script>

<script type="text/javascript">
$(document).ready(function() {
  $('.slideshow1').cycle({
    fx: 'fade' // choose your transition type, ex: fade, scrollUp, shuffle, fade looks best
  });
});
</script>




 


  <div class="slideshow1">
  <%= image_tag("logo_mace.jpg", :alt => "Mace")%>
  <%= image_tag("logo_painter.jpg", :alt => "Painter")%>
  <%= image_tag("logo_lynches.jpg", :alt => "lynches")%></h1>
  <br><br><br><br><br>
  <h2>stmichaelsgfc2013@gmail.com
  <br><br>
  <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-like" data-href="https://www.facebook.com/stmichaels.gfc?hc_location=stream" data-send="false" data-layout="button_count" data-width="500" data-show-faces="true" data-font="verdana"></div>
 <br><br> <a href= "sign_up_newsletters/new">Receive a Monthly Newsletter</a>
  </h2>
  </div>

  
    
    
    <%= yield %>
    </div>
    <br><br><br>
 <br><br>
</body>
</html>