config/routes.rb
StMichaelsGFC::Application.routes.draw do
 
  resources :players_profiles
  resources :teams
  resources :sign_up_newsletters
  resources :newsletter_st_micahels_gfcs
  resources :newsletters
  resources :users
  resources :sessions
  resources :photos
  resources :events
  resources :pitch_bookings 

  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  root :to => "admin#index"
 
   match "club_history" => "club_history#index" 
   match "fixtures" => "events#index"
   match "admin" => "admin#index"
    match "stmichaelsgfc" => "stmichaelsgfc#index"
  

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  attr_accessible :date, :email, :name, :phone, :reason, :text
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :Age_Category, :Date, :Location, :Opponent, :Time
  
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  attr_accessible :content, :date, :string, :title
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :caption
  attr_accessible :image
  
  has_attached_file :image
    
  
end

app/models/pitch_booking.rb
class PitchBooking < ActiveRecord::Base
  attr_accessible :date, :email, :name, :phone, :reason
end

app/models/players_profile.rb
class PlayersProfile < ActiveRecord::Base
  attr_accessible :age_category, :date_of_birth, :name
  attr_accessible :pic
  
  has_attached_file :pic
end

app/models/sign_up_newsletter.rb
class SignUpNewsletter < ActiveRecord::Base
  attr_accessible :email, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/pitch_bookings_controller.rb
class PitchBookingsController < ApplicationController
  # GET /pitch_bookings
  # GET /pitch_bookings.json
  def index
    @pitch_bookings = PitchBooking.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pitch_bookings }
    end
  end

  # GET /pitch_bookings/1
  # GET /pitch_bookings/1.json
  def show
    @pitch_booking = PitchBooking.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pitch_booking }
    end
  end

  # GET /pitch_bookings/new
  # GET /pitch_bookings/new.json
  def new
    @pitch_booking = PitchBooking.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pitch_booking }
    end
  end

  # GET /pitch_bookings/1/edit
  def edit
    @pitch_booking = PitchBooking.find(params[:id])
  end

  # POST /pitch_bookings
  # POST /pitch_bookings.json
  def create
    @pitch_booking = PitchBooking.new(params[:pitch_booking])

    respond_to do |format|
      if @pitch_booking.save
        format.html { redirect_to @pitch_booking, notice: 'Pitch booking was successfully created.' }
        format.json { render json: @pitch_booking, status: :created, location: @pitch_booking }
      else
        format.html { render action: "new" }
        format.json { render json: @pitch_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pitch_bookings/1
  # PUT /pitch_bookings/1.json
  def update
    @pitch_booking = PitchBooking.find(params[:id])

    respond_to do |format|
      if @pitch_booking.update_attributes(params[:pitch_booking])
        format.html { redirect_to @pitch_booking, notice: 'Pitch booking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pitch_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pitch_bookings/1
  # DELETE /pitch_bookings/1.json
  def destroy
    @pitch_booking = PitchBooking.find(params[:id])
    @pitch_booking.destroy

    respond_to do |format|
      format.html { redirect_to pitch_bookings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/club_history_helper.rb
module ClubHistoryHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/pitch_bookings_helper.rb
module PitchBookingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/pitch_bookings/_form.html.erb
<%= form_for(@pitch_booking) do |f| %>
  <% if @pitch_booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pitch_booking.errors.count, "error") %> prohibited this pitch_booking from being saved:</h2>

      <ul>
      <% @pitch_booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :reason %><br />
    <%= f.text_area :reason %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.number_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pitch_bookings/edit.html.erb
<div id= "right_box">
<h1>Editing pitch_booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @pitch_booking %> |
<%= link_to 'Back', pitch_bookings_path %>
<br><br>
</div>
<br><br>

app/views/pitch_bookings/index.html.erb
<div id= "right_box">
<h1>Book St.Michaels Pitch/Club House</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Reason</th>
    <th>Date</th>
    <th>Phone</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pitch_bookings.each do |pitch_booking| %>
  <tr>
    <td><%= pitch_booking.name %></td>
    <td><%= pitch_booking.reason %></td>
    <td><%= pitch_booking.date %></td>
    <td><%= pitch_booking.phone %></td>
    <td><%= pitch_booking.email %></td>
    <td><%= link_to 'Show', pitch_booking %></td>
    <td><%= link_to 'Edit', edit_pitch_booking_path(pitch_booking) %></td>
    <td><%= link_to 'Destroy', pitch_booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pitch booking', new_pitch_booking_path %>
<br><br>
<%= link_to 'Back', admin_path %>
<br><br>
</div>
<br><br>

app/views/pitch_bookings/new.html.erb
<div id= "right_box">
<h1>Book the Pitch for Events/Fixtures</h1>

<%= render 'form' %>


<br><br>
</div>
<br><br>

app/views/pitch_bookings/show.html.erb
<div id= "right_box">
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @pitch_booking.name %>
</p>

<p>
  <b>Reason:</b>
  <%= @pitch_booking.reason %>
</p>

<p>
  <b>Date:</b>
  <%= @pitch_booking.date %>
</p>

<p>
  <b>Phone:</b>
  <%= @pitch_booking.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @pitch_booking.email %>
</p>


<%= link_to 'Edit', edit_pitch_booking_path(@pitch_booking) %> 
<%= link_to 'Back', pitch_bookings_path %>

<br><br>
</div>
<br><br>