config/routes.rb
StMichaelsGFC::Application.routes.draw do
 
  resources :players_profiles
  resources :teams
  resources :sign_up_newsletters
  resources :newsletter_st_micahels_gfcs
  resources :newsletters
  resources :users
  resources :sessions
  resources :photos
  resources :events
  resources :pitch_bookings 

  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  root :to => "admin#index"
 
   match "club_history" => "club_history#index" 
   match "fixtures" => "events#index"
   match "admin" => "admin#index"
    match "stmichaelsgfc" => "stmichaelsgfc#index"
  

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  attr_accessible :date, :email, :name, :phone, :reason, :text
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :Age_Category, :Date, :Location, :Opponent, :Time
  
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  attr_accessible :content, :date, :string, :title
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :caption
  attr_accessible :image
  
  has_attached_file :image
    
  
end

app/models/pitch_booking.rb
class PitchBooking < ActiveRecord::Base
  attr_accessible :date, :email, :name, :phone, :reason
end

app/models/players_profile.rb
class PlayersProfile < ActiveRecord::Base
  attr_accessible :age_category, :date_of_birth, :name
  attr_accessible :pic
  
  has_attached_file :pic
end

app/models/sign_up_newsletter.rb
class SignUpNewsletter < ActiveRecord::Base
  attr_accessible :email, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/club_history_helper.rb
module ClubHistoryHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<div id= "right_box">
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Age_Category %><br />
    <%= f.text_field :Age_Category %>
  </div>
  <div class="field">
    <%= f.label :Time %><br />
    <%= f.time_select :Time %>
  </div>
  <div class="field">
    <%= f.label :Date %><br />
    <%= f.date_select :Date %>
  </div>
  <div class="field">
    <%= f.label :Location %><br />
    <%= f.text_field :Location %>
  </div>
  <div class="field">
    <%= f.label :Opponent %><br />
    <%= f.text_field :Opponent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/events/edit.html.erb
<div id= "right_box">
<h1>Editing Event</h1>

<%= render 'form' %>
<br><br>
<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>


<br><br>
</div>
<br><br>

app/views/events/index.html.erb
<div id= "right_box">
<h1>Upcoming Events</h1>

<table>
  <tr>
    <th>Age Category</th>
    <th>Time</th>
    <th>Date</th>
    <th>Location</th>
    <th>Opponent</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.Age_Category %></td>
    <td><%= event.Time %></td>
    <td><%= event.Date %></td>
    <td><%= event.Location %></td>
    <td><%= event.Opponent %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %><br><br>
<%= link_to 'Back', admin_path %>
<br><br>
</div>
<br><br>

app/views/events/new.html.erb
<div id= "right_box">
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>
<br><br>
</div>
<br><br>

app/views/events/show.html.erb
<div id= "right_box">
<p id="notice"><%= notice %></p>

<p>
  <b>Age category:</b>
  <%= @event.Age_Category %>
</p>

<p>
  <b>Time:</b>
  <%= @event.Time %>
</p>

<p>
  <b>Date:</b>
  <%= @event.Date %>
</p>

<p>
  <b>Location:</b>
  <%= @event.Location %>
</p>

<p>
  <b>Opponent:</b>
  <%= @event.Opponent %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>


<br><br>
</div>
<br><br>