config/routes.rb
StMichaelsGFC::Application.routes.draw do
 
  resources :players_profiles
  resources :teams
  resources :sign_up_newsletters
  resources :newsletter_st_micahels_gfcs
  resources :newsletters
  resources :users
  resources :sessions
  resources :photos
  resources :events
  resources :pitch_bookings 

  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  root :to => "admin#index"
 
   match "club_history" => "club_history#index" 
   match "fixtures" => "events#index"
   match "admin" => "admin#index"
    match "stmichaelsgfc" => "stmichaelsgfc#index"
  

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  attr_accessible :date, :email, :name, :phone, :reason, :text
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :Age_Category, :Date, :Location, :Opponent, :Time
  
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  attr_accessible :content, :date, :string, :title
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :caption
  attr_accessible :image
  
  has_attached_file :image
    
  
end

app/models/pitch_booking.rb
class PitchBooking < ActiveRecord::Base
  attr_accessible :date, :email, :name, :phone, :reason
end

app/models/players_profile.rb
class PlayersProfile < ActiveRecord::Base
  attr_accessible :age_category, :date_of_birth, :name
  attr_accessible :pic
  
  has_attached_file :pic
end

app/models/sign_up_newsletter.rb
class SignUpNewsletter < ActiveRecord::Base
  attr_accessible :email, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/sign_up_newsletters_controller.rb
class SignUpNewslettersController < ApplicationController
  # GET /sign_up_newsletters
  # GET /sign_up_newsletters.json
  def index
    @sign_up_newsletters = SignUpNewsletter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sign_up_newsletters }
    end
  end

  # GET /sign_up_newsletters/1
  # GET /sign_up_newsletters/1.json
  def show
    @sign_up_newsletter = SignUpNewsletter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sign_up_newsletter }
    end
  end

  # GET /sign_up_newsletters/new
  # GET /sign_up_newsletters/new.json
  def new
    @sign_up_newsletter = SignUpNewsletter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sign_up_newsletter }
    end
  end

  # GET /sign_up_newsletters/1/edit
  def edit
    @sign_up_newsletter = SignUpNewsletter.find(params[:id])
  end

  # POST /sign_up_newsletters
  # POST /sign_up_newsletters.json
  def create
    @sign_up_newsletter = SignUpNewsletter.new(params[:sign_up_newsletter])

    respond_to do |format|
      if @sign_up_newsletter.save
        format.html { redirect_to @sign_up_newsletter, notice: 'Sign up newsletter was successfully created.' }
        format.json { render json: @sign_up_newsletter, status: :created, location: @sign_up_newsletter }
      else
        format.html { render action: "new" }
        format.json { render json: @sign_up_newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sign_up_newsletters/1
  # PUT /sign_up_newsletters/1.json
  def update
    @sign_up_newsletter = SignUpNewsletter.find(params[:id])

    respond_to do |format|
      if @sign_up_newsletter.update_attributes(params[:sign_up_newsletter])
        format.html { redirect_to @sign_up_newsletter, notice: 'Sign up newsletter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sign_up_newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sign_up_newsletters/1
  # DELETE /sign_up_newsletters/1.json
  def destroy
    @sign_up_newsletter = SignUpNewsletter.find(params[:id])
    @sign_up_newsletter.destroy

    respond_to do |format|
      format.html { redirect_to sign_up_newsletters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/club_history_helper.rb
module ClubHistoryHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sign_up_newsletters_helper.rb
module SignUpNewslettersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sign_up_newsletters/_form.html.erb
<%= form_for(@sign_up_newsletter) do |f| %>
  <% if @sign_up_newsletter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sign_up_newsletter.errors.count, "error") %> prohibited this sign_up_newsletter from being saved:</h2>

      <ul>
      <% @sign_up_newsletter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
      <br><br>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
    <br><br>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
    <br><br>
  </div>
  <div class="actions">
    <%= f.submit %>
    <br><br>
  </div>
<% end %>

app/views/sign_up_newsletters/edit.html.erb
<div id= "right_box">
<h1>Editing Sign Up for Newsletter</h1>

<%= render 'form' %>

<%= link_to 'Show', @sign_up_newsletter %> |
<%= link_to 'Back', sign_up_newsletters_path %>
<br><br>
</div>
<br><br>

app/views/sign_up_newsletters/index.html.erb
<div id= "right_box">
<h1>List of Signed Up</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sign_up_newsletters.each do |sign_up_newsletter| %>
  <tr>
    <td><%= sign_up_newsletter.name %></td>
    <td><%= sign_up_newsletter.email %></td>
    <td><%= link_to 'Show', sign_up_newsletter %></td>
    <td><%= link_to 'Edit', edit_sign_up_newsletter_path(sign_up_newsletter) %></td>
    <td><%= link_to 'Destroy', sign_up_newsletter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sign up newsletter', new_sign_up_newsletter_path %>
<br><br>
</div>
<br><br>

app/views/sign_up_newsletters/new.html.erb
<div id= "right_box">
<h1>Sign Up to Receive a Monthly Newsletter</h1>

<%= render 'form' %>

<%= link_to 'Back', sign_up_newsletters_path %>
<br><br>
</div>
<br><br>

app/views/sign_up_newsletters/show.html.erb
<div id= "right_box">
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @sign_up_newsletter.name %>
</p>

<p>
  <b>Email:</b>
  <%= @sign_up_newsletter.email %>
</p>


<%= link_to 'Edit', edit_sign_up_newsletter_path(@sign_up_newsletter) %>|
<%= link_to 'New Sign Up', new_sign_up_newsletter_path %>

<br><br>
</div>
<br><br>